# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vkapp_luna' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'SDWebImage'
pod 'RealmSwift'
pod 'PromiseKit'
  # Pods for vkapp_luna

end
